name: CI

on:
  push:
    branches: 
        - master
        - dev
        - gcp

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
        
    # - name: Deploy to Firebase Staging
    #   if: github.ref == 'refs/heads/dev'
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: "deploy --only hosting:staging"
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    #     PROJECT_ID: 'goodnews-2c75a'

    # - name: Deploy to Firebase Prod
    #   if: github.ref == 'refs/heads/master'
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: "deploy --only hosting:prod"
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    #     PROJECT_ID: 'goodnews-2c75a'
        
    - name: Copy to Bucket Staging
      if: github.ref == 'refs/heads/gcp'
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: thegoodnewscoronavirus
        APPLICATION_CREDENTIALS: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGhlZ29vZG5ld3Njb3JvbmF2aXJ1cyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjhhYzZmY2M1OGZhZmQ2YjZiYTExZTY5YTRmMTY4ZmFjZTI5NDg5NmUiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRENWMkFGYW8rMVJHUC9cbmVhRkdSWktXOTZ0YURCb0x6Y3dIeFJhTVFhM1RGZGM1MUR6NTByam1EOG9lcmlseFZzdEZVLzJ0bHpsbmh1WFdcblFwQmJXVnNVbWV2RlVWdFhLQTZBdkZySE94RXFMMG9yaXpLaFVoMzd1eXltWDl1Unl3alBjRkRMSmoxVkVRTjNcbkd1VjFwQW8zMGgxOVMvdmhmT3RDY2szc0FwdkM4VEt4ZjlJZ1hWSkdpME1JQkd4WjkyeXM1dTRkVFR1dmJJSkFcbk5NcUpHaFhmMHkwWE5Iem9veDRIM0JBOHQ5enVnNi9nVU9YRkR5ZTJVWVA1V0lGUjBJczBESERMbWFXcEVZSGRcbjBObTAvQUVpVWpsMCsvTURmVnoyK2ZNa1BBSlYyNTdOSFVsNVNUTURtZlNTbU5QOWxZRDRLd1N3RVhBVENNL29cbmJvMmVpVEUxQWdNQkFBRUNnZ0VBRmJaaFdmbVAyTGF0WFd1Zll4Uit6ak1aaDlQMlRQOVBIa2NjdjhyT3V0aWpcbjFTZ3JMOVlsSmo3NVcvZ2xWUzVYUTRXZ3YvWTNTYU8rcGZPRjRVN1lhRExTTHBkcVZ4QjRubFZzNXZsb2I0Z2RcbkIwUmtBYllFOTR6djdoNmpqMlJadGFOY3czV2dRSkxJQ2xTTThsbkRjbjBkSWxTTTdhSmhQbWs2MzNWakphSlBcbkZWVjNwa3hXcnppbUI2NUxMSWFnYTRpOXNJdTVXOXRXanVMMDNpbFZzNlNrOWRJVFlOYzR2blFqaFZ0byt3M0JcbktMd1E1SlJFUXJvdDFweFFPd2UrYmY1S0FmV1hHV1NYRjF6bm92Zzk5OUFsbno0MkhoZTQ3VmREaDZpWGQrVnVcbitaRmwvQ3pubk9IN1Y0LzFIVEFiVHR4eldJdWxxdFdlSFRTYlpDckZRUUtCZ1FEc1FJUjRPOG9Vc3RBWTlHNzBcbkZFUVF6NlVCNU81OU9sVGlibEo0d1hDYU5PM0kxTEtDSDEwdEZZRG8wWlhXSG12Y3ZWcnN3N2QwNURqd0dMQWdcbkw5RmxuUXI0SGhDQUw2c1N0ZTZyN2M3TUlJRlpZckxJY2hGTFQzYXZuZG15NE5pdDNmNElteE1sSFNUOXdRbUtcbmJPZzI4N2xSQkwxaHVJMysvK215SGR2YmVRS0JnUURTbGdZRDlqSnRvYjFidG01SC9wZTBkSW1ONmlTamV3TDdcblJvbTdRbklKVGMvbk55UzUzTlRpamFHaitZcEdYQTlKUzNtb0pkK2JGTGhveG9BQXFGTnRSZ0dLa2YrMFRKYVlcbnNaR0UxekdtU1NMOUNzODh2UDNtUTAxQUVQazk0M2FqZlo1bEdzNWNiMUVWaUR0SVJEUndjV1hPb0Q3S2doVS9cbi9nZnl3dEpZblFLQmdRQ0w0U3ROMFFDMlBxVXRrVlE4V2Q5dklMSnZLNi8xSDF0dzhhY003bU9RT2pScnkxdWhcbjVaWVNnbi9mMlcvZzVnUXhIMEE5blNmN0lzRi9qdTZCTUM3SC9qS25jNDJMaUMyL0YwOG9KdFpoVUFHbC9lVWlcbi96NjBHMm1IVTJ1NUdKM1NXL1R6L1hWWmJTY2d3M0cxcndQU3ZYMkV0Y3kzbGtFa3NUc2FCY25ONlFLQmdRRExcbnA3TGhtZk5pK3d3NTZjLzFhRTRtZ3AyVTFWL2hpbEZ6Mk4vU2JZd0RXM0U0MXFkNTZBc3BubmM0TVZoOGV3TjlcbmlyUjQzVWZHbnQ5STFNOXQwMXY3VGJ5bjJsSkVkOTBjaG4ySXp1U0JRREhLTGU0RmUzREFnMDN1SzN3ZlVoK21cbk5SSStEUktOYWtvc1hMZVlSLzIrMEt2NGpCaXRsK2dkSHZ0bzF1aStNUUtCZ1FDcFd3dFVjYWtGb1h2bEFUcWhcbnBQSFltTWxtVTNuRytHa3BDcks5dVdjc2czTnJsWHlzTXNUOVFXU1hsTFphSW1lSkV5YXFxSVdPbnJBVVIrV0tcbjJOZWUwd0p1UzBrYVE3bENKY0FXOTVxakhNdy9YZGhGZDlCWEVsQjQvSVFGOWhNbGh1bUlSTXVGazRlT2h4WmZcbjdYTVBMVGVWWmRpUDh0anZQMGZ3TC91bnR3PT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJob3N0aW5nQHRoZWdvb2RuZXdzY29yb25hdmlydXMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwNzA3Mzg5NTMwMDY3NjY2MjIxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9ob3N0aW5nJTQwdGhlZ29vZG5ld3Njb3JvbmF2aXJ1cy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
        CLI: gsutil
      with:
        - args: -m rsync -d -r ./build ${{secrets.STAGING_BUCKET}}
        - args: -m setmeta -h "Cache-Control:private, max-age=0, no-transform" ${{secrets.STAGING_BUCKET}}/*.* 
      
    # - name: Set cache
    #   if: github.ref == 'refs/heads/gcp'
    #   uses: actions-hub/gcloud@master
    #   env:
    #     PROJECT_ID: thegoodnewscoronavirus
    #     APPLICATION_CREDENTIALS: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGhlZ29vZG5ld3Njb3JvbmF2aXJ1cyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjhhYzZmY2M1OGZhZmQ2YjZiYTExZTY5YTRmMTY4ZmFjZTI5NDg5NmUiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRENWMkFGYW8rMVJHUC9cbmVhRkdSWktXOTZ0YURCb0x6Y3dIeFJhTVFhM1RGZGM1MUR6NTByam1EOG9lcmlseFZzdEZVLzJ0bHpsbmh1WFdcblFwQmJXVnNVbWV2RlVWdFhLQTZBdkZySE94RXFMMG9yaXpLaFVoMzd1eXltWDl1Unl3alBjRkRMSmoxVkVRTjNcbkd1VjFwQW8zMGgxOVMvdmhmT3RDY2szc0FwdkM4VEt4ZjlJZ1hWSkdpME1JQkd4WjkyeXM1dTRkVFR1dmJJSkFcbk5NcUpHaFhmMHkwWE5Iem9veDRIM0JBOHQ5enVnNi9nVU9YRkR5ZTJVWVA1V0lGUjBJczBESERMbWFXcEVZSGRcbjBObTAvQUVpVWpsMCsvTURmVnoyK2ZNa1BBSlYyNTdOSFVsNVNUTURtZlNTbU5QOWxZRDRLd1N3RVhBVENNL29cbmJvMmVpVEUxQWdNQkFBRUNnZ0VBRmJaaFdmbVAyTGF0WFd1Zll4Uit6ak1aaDlQMlRQOVBIa2NjdjhyT3V0aWpcbjFTZ3JMOVlsSmo3NVcvZ2xWUzVYUTRXZ3YvWTNTYU8rcGZPRjRVN1lhRExTTHBkcVZ4QjRubFZzNXZsb2I0Z2RcbkIwUmtBYllFOTR6djdoNmpqMlJadGFOY3czV2dRSkxJQ2xTTThsbkRjbjBkSWxTTTdhSmhQbWs2MzNWakphSlBcbkZWVjNwa3hXcnppbUI2NUxMSWFnYTRpOXNJdTVXOXRXanVMMDNpbFZzNlNrOWRJVFlOYzR2blFqaFZ0byt3M0JcbktMd1E1SlJFUXJvdDFweFFPd2UrYmY1S0FmV1hHV1NYRjF6bm92Zzk5OUFsbno0MkhoZTQ3VmREaDZpWGQrVnVcbitaRmwvQ3pubk9IN1Y0LzFIVEFiVHR4eldJdWxxdFdlSFRTYlpDckZRUUtCZ1FEc1FJUjRPOG9Vc3RBWTlHNzBcbkZFUVF6NlVCNU81OU9sVGlibEo0d1hDYU5PM0kxTEtDSDEwdEZZRG8wWlhXSG12Y3ZWcnN3N2QwNURqd0dMQWdcbkw5RmxuUXI0SGhDQUw2c1N0ZTZyN2M3TUlJRlpZckxJY2hGTFQzYXZuZG15NE5pdDNmNElteE1sSFNUOXdRbUtcbmJPZzI4N2xSQkwxaHVJMysvK215SGR2YmVRS0JnUURTbGdZRDlqSnRvYjFidG01SC9wZTBkSW1ONmlTamV3TDdcblJvbTdRbklKVGMvbk55UzUzTlRpamFHaitZcEdYQTlKUzNtb0pkK2JGTGhveG9BQXFGTnRSZ0dLa2YrMFRKYVlcbnNaR0UxekdtU1NMOUNzODh2UDNtUTAxQUVQazk0M2FqZlo1bEdzNWNiMUVWaUR0SVJEUndjV1hPb0Q3S2doVS9cbi9nZnl3dEpZblFLQmdRQ0w0U3ROMFFDMlBxVXRrVlE4V2Q5dklMSnZLNi8xSDF0dzhhY003bU9RT2pScnkxdWhcbjVaWVNnbi9mMlcvZzVnUXhIMEE5blNmN0lzRi9qdTZCTUM3SC9qS25jNDJMaUMyL0YwOG9KdFpoVUFHbC9lVWlcbi96NjBHMm1IVTJ1NUdKM1NXL1R6L1hWWmJTY2d3M0cxcndQU3ZYMkV0Y3kzbGtFa3NUc2FCY25ONlFLQmdRRExcbnA3TGhtZk5pK3d3NTZjLzFhRTRtZ3AyVTFWL2hpbEZ6Mk4vU2JZd0RXM0U0MXFkNTZBc3BubmM0TVZoOGV3TjlcbmlyUjQzVWZHbnQ5STFNOXQwMXY3VGJ5bjJsSkVkOTBjaG4ySXp1U0JRREhLTGU0RmUzREFnMDN1SzN3ZlVoK21cbk5SSStEUktOYWtvc1hMZVlSLzIrMEt2NGpCaXRsK2dkSHZ0bzF1aStNUUtCZ1FDcFd3dFVjYWtGb1h2bEFUcWhcbnBQSFltTWxtVTNuRytHa3BDcks5dVdjc2czTnJsWHlzTXNUOVFXU1hsTFphSW1lSkV5YXFxSVdPbnJBVVIrV0tcbjJOZWUwd0p1UzBrYVE3bENKY0FXOTVxakhNdy9YZGhGZDlCWEVsQjQvSVFGOWhNbGh1bUlSTXVGazRlT2h4WmZcbjdYTVBMVGVWWmRpUDh0anZQMGZ3TC91bnR3PT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJob3N0aW5nQHRoZWdvb2RuZXdzY29yb25hdmlydXMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwNzA3Mzg5NTMwMDY3NjY2MjIxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9ob3N0aW5nJTQwdGhlZ29vZG5ld3Njb3JvbmF2aXJ1cy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
    #     CLI: gsutil
    #   with:
        # args: -m setmeta -h "Cache-Control:private, max-age=0, no-transform" ${{secrets.STAGING_BUCKET}}/*.* 